on: 
  pull_request:
  issues:

name: "Auto message for PR's and Issues"

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for opening your first issue for datefixR! @nathansam will reply as soon as possible'
        pr-message: 'Thank you for opening your first pull request! You will receive a response soon.'